name: 01 - Hello

on: 
    push:
        branches: [main,develop]

jobs:
    hello: 
        runs-on: ubuntu-22.04

        steps:
            - name: Saludar
              run: echo "Hola desde github actions"
            
            - name: Ver fecha del runner
              run: date

            - name: Ver archivos disponibles
              run: ls -la   